version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: cinema_user
      POSTGRES_PASSWORD: cinema_password
      POSTGRES_DB: cinema_time
    ports:
      - "5432:5432"

  server:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://cinema_user:cinema_password@db:5432/cinema_time
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000/api